version: '3.3'

services:
 lb:
  image: jfahrer/lb:v3
  build: ./proxy.conf
  depends_on:
   - webapp
  ports:
   - 80:80
  environment:
   - PROXY_UPSTREAM

 pg:
  image: postgres:9.6-alpine
  environment:
   - POSTGRES_DB
   - POSTGRES_USER
   - POSTGRES_PASSWORD
  volumes:
   - pg-data:/var/lib/postgresql/data

 webapp:
  image: jfahrer/demo_web_app:wait_for_pg
  depends_on:
   - pg
  environment:
   - POSTGRES_DB
   - POSTGRES_USER
   - POSTGRES_PASSWORD
   - POSTGRES_HOST

 alpine:
  image: alpine:latest
  stdin_open: true
  tty: true
  command: sh

volumes:
 pg-data: 
