version: '3.3'

services:
 webapp:
  image: jfahrer/demo_web_app:latest
  env_file:
   - ./app.env
  ports:
   - 9292:9292

 pg:
  image: postgres:9.6.6-alpine
  env_file:
   - ./db.env
  volumes:
   - pg-data:/var/lib/postgresql/data

volumes:
 pg-data: 
