version: '3.3'

services:
  pg:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./db/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql

  webapp:
    image: python_webapp
    build: .
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
    volumes:
      - ./app:/app
    depends_on:
      - pg

  lb:
    image: jfahrer/lb:v3
    ports:
      - 80:80
    environment:
      - PROXY_UPSTREAM
    depends_on:
      - webapp
    